BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "APP_VERSION" (
	"App_ID"	INTEGER UNIQUE,
	"App_VER"	TEXT,
	"App_VERDATE"	TEXT,
	"App_UPGRADEDATE"	TEXT,
	PRIMARY KEY("App_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "USER" (
	"Usr_ID"	INTEGER UNIQUE,
	"Usr_NAME"	TEXT NOT NULL DEFAULT 'USER',
	"Usr_PW"	TEXT,
	"Usr_GROUP"	TEXT DEFAULT 'GROUP',
	PRIMARY KEY("Usr_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "NOTEMEDIA" (
	"Nmd_ID"	INTEGER UNIQUE,
	"Nmd_DESCRIPTION"	TEXT,
	"Nmd_MEDIA"	BLOB,
	"Nmd_THUMB"	BLOB,
	"Nmd_Not_ID"	INTEGER NOT NULL,
	"Nmd_DATETIME"	TEXT,
	FOREIGN KEY("Nmd_Not_ID") REFERENCES "NOTES"("Not_ID"),
	PRIMARY KEY("Nmd_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "NOTETYPES" (
	"Ntp_ID"	INTEGER UNIQUE,
	"Ntp_NAME"	TEXT,
	"Ntp_DESCRIPTION"	TEXT,
	PRIMARY KEY("Ntp_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "NOTES" (
	"Not_ID"	INTEGER UNIQUE,
	"Not_NAME"	TEXT,
	"Not_NOTES"	TEXT,
	"Not_DATETIME"	TEXT,
	"Not_Usr_ID"	INTEGER NOT NULL,
	"Not_Ntp_ID"	TEXT,
	"Not_BODY"	INTEGER,
	"Not_MIND"	INTEGER,
	"Not_EMOTION"	INTEGER,
	"Not_MONTHLY"	INTEGER,
	"Not_WEEKLY"	INTEGER,
	"Not_DAILY"	INTEGER,
	"Not_INSTRUMENT"	TEXT,
	"Not_PNL"	NUMERIC,
	"Not_HASHTAG"	TEXT,
	FOREIGN KEY("Not_Usr_ID") REFERENCES "USER"("Usr_ID"),
	FOREIGN KEY("Not_Ntp_ID") REFERENCES "NOTETYPES"("Ntp_ID"),
	PRIMARY KEY("Not_ID" AUTOINCREMENT)
);
INSERT INTO "USER" VALUES (1,'USER',NULL,'GROUP');
INSERT INTO "NOTETYPES" VALUES (1,'Trade','Review Your Trade');
INSERT INTO "NOTETYPES" VALUES (2,'Daily','End of Day Review');
INSERT INTO "NOTETYPES" VALUES (3,'PreWeek','Pre-Week Notes');
INSERT INTO "NOTETYPES" VALUES (4,'PostWeek','Post Week Review');
INSERT INTO "NOTETYPES" VALUES (5,'Rules','Rules You Trade By');
INSERT INTO "NOTETYPES" VALUES (6,'Strategy','Strategies for your Trade');
INSERT INTO "NOTETYPES" VALUES (7,'Plan','Lay Out Your Plan');
INSERT INTO "NOTETYPES" VALUES (8,'Workout','Workout Notes');
INSERT INTO "NOTETYPES" VALUES (9,'Diet','Diet Notes');
INSERT INTO "NOTETYPES" VALUES (10,'Sleep','Sleep Notes');
INSERT INTO "NOTETYPES" VALUES (11,'Meditation','Meditation Notes');
INSERT INTO "NOTETYPES" VALUES (12,'Thoughts','Current Thoughts');
INSERT INTO "NOTETYPES" VALUES (13,'Ideas','Ideas to research');
INSERT INTO "NOTETYPES" VALUES (14,'Triggers','What Triggers Emotion');
INSERT INTO "NOTETYPES" VALUES (15,'Predictions','Predicted Trade Outcomes');
INSERT INTO "NOTETYPES" VALUES (16,'Backtest','Backtesting Notes');
INSERT INTO "NOTETYPES" VALUES (17,'Other','Other Notes');
INSERT INTO "NOTETYPES" VALUES (18,'Template','Create a Note Template');

CREATE TRIGGER cleanupMedia
 BEFORE DELETE on NOTES
 BEGIN
	DELETE from NOTEMEDIA where Nmd_Not_ID = OLD.Not_ID;
 END;
COMMIT;
